/*-
 * Copyright (c) 2013, 2014 Jason Lingle
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the author nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#include <math.h>
#include <stdio.h>

#include "math/coords.h"

int main(void) {
  unsigned i;
  signed val;
  double f, pi = acos(-1);
  printf("/*\n"
         "  This file was automatically generated by gen_trigtab.c.\n"
         "  Do not edit.\n"
         " */\n"
         "#ifdef HAVE_CONFIG_H\n"
         "#include <config.h>\n"
         "#endif\n"
         "#include \"math/coords.h\"\n"
         "const zo_scaling_factor zo_cosine[%d] = {\n",
         ZO_COSINE_COUNT);
  for (i = 0; i < ZO_COSINE_COUNT; ++i) {
    f = i * 2.0 * pi / (double)ZO_COSINE_COUNT;
    f = cos(f);
    val = (signed)(f * ZO_SCALING_FACTOR_MAX);
    printf("  %d,\n", val);
  }

  printf("};\n");

  printf("const unsigned char fisqrt_table[FISQRT_CNT] = {\n");
  for (i = 0; i < FISQRT_CNT; ++i)
    printf("  %d,\n", (unsigned char)sqrt((float)i));
  printf("};\n");

  return 0;
}
